# Generated by Django 4.2.13 on 2024-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="item_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
